# Publish all joint states -----------------------------------
#joint_state_controller:
#  type: joint_state_controller/JointStateController
#  publish_rate: 30

controller_list:
  - name: setFollowTrajectory
    type: FollowJointTrajectory
    joints:
       - mico_joint_1
       - mico_joint_2
       - mico_joint_3
       - mico_joint_4
       - mico_joint_5
       - mico_joint_6

#fingers_controller:
#  type: "position_controllers/GripperActionController"
# joints:
# - mico_joint_finger_1
# - mico_joint_finger_2
# - mico_joint_finger_1_distal
# - mico_joint_finger_2_distal
#  joint: mico_joint_finger_1
#  stall_velocity_threshold: 0.0
