#---
#sensors:
# - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
#   point_cloud_topic: /camera/depth_registered/points
#   max_range: 2.0
#   padding_offset: .04
#   padding_scale: 1.0
#   point_subsample: 4
#   filtered_cloud_topic: /octomap_filter/near_filtered_cloud

# - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
#   point_cloud_topic: /octomap_filter/near_filtered_cloud
#   max_range: 2.0
#   padding_offset: .04
#   padding_scale: 1.0
#   point_subsample: 1
#   filtered_cloud_topic: /octomap_filter/far_filtered_clou


# sensors:
#   - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
#     image_topic: /camera/depth_registered/image_raw
#     queue_size: 5
#     near_clipping_plane_distance: 0.1
#     far_clipping_plane_distance: 2.0
#     shadow_threshold: 0.2
#     padding_scale: 4.0
#     padding_offset: 0.03
#     filtered_cloud_topic: filtered_cloud